version: "3.8"

services:
  db:
    image: postgis/postgis:16-3.4
    restart: unless-stopped
    environment:
      POSTGRES_USER: runner
      POSTGRES_PASSWORD: runner
      POSTGRES_DB: route_planner
    ports:
      - "5432:5432"
    volumes:
      - route_planner_db:/var/lib/postgresql/data

volumes:
  route_planner_db:
