import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/db";
import { buildGpx } from "@/lib/gpx";

export async function GET(_req: NextRequest, { params }: { params: { routeOptionId: string } }) {
  const route = await prisma.routeOption.findUnique({ where: { id: params.routeOptionId } });
  if (!route) return NextResponse.json({ error: "Route not found" }, { status: 404 });

  const geojson = route.geojson as any;
  const coords: [number, number][] = geojson?.geometry?.coordinates ?? [];

  const gpx = buildGpx({
    name: route.name,
    coordinates: coords,
    description: `${route.distanceKm.toFixed(2)}km ${route.routeType} route — generated by Run Where?
  });

  return new NextResponse(gpx, {
    headers: {
      "Content-Type": "application/gpx+xml",
      "Content-Disposition": `attachment; filename="${route.name.replace(/\s+/g, "_")}.gpx"`,
    },
  });
}
